[project]
name = "PaperQuant"
version = "0.2.0"
description = "An interactive & open-source paper trading platform for algorithmic traders."
authors = [
    {name = "DikshitRJ",email = "ourledtv@gmail.com"}
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "yfinance (>=1.1.0,<2.0.0)",
    "diskcache (>=5.6.3,<6.0.0)",
    "pyzmq (>=27.1.0,<28.0.0)",
    "pandas (>=2.0.0,<3.0.0)",
    "numpy (>=1.24.0,<3.0.0)",
    "fastapi (>=0.115.0,<1.0.0)",
    "uvicorn[standard] (>=0.30.0,<1.0.0)",
    "websockets (>=12.0,<14.0)",
    "python-multipart (>=0.0.9,<1.0.0)"
]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
ignore = ["BLE001", "LOG015", "B008", "RUF012", "ASYNC230", "DTZ005", "PIE790", "SIM102", "N999"]
